### ISSUE TITLE
Graphical bug in profile picture context menu

### ISSUE THREAD

**Issue by VictorieeMan** [coracle-social/coracle#126]
In the expandable menu on the personal profile picture on coracle.social, there is a hovering notification blip from the Relay tab. When marking the little orange dot with my cursor, it highlights the Relay tab; see picture. Blur arrow is just to point at the dot.

![image](https://github.com/coracle-social/coracle/assets/59509525/3d544d1c-a44e-4e75-8336-8b13c5c429dc)

I've replicated this on both Mozilla and Chromium browsers.

**Comment by staab** [comment]
Thanks! Fixed in the next release.
