### ISSUE TITLE
Mixed content - certificate warning in browser

### ISSUE THREAD

**Issue by Renebr02** [coracle-social/coracle#138]
On Coracle Tabs "apps" and network "global" i get ssl certificate errors or warnings page: "Not secure cause mixed content". An app or plugin retrieves unsecured graphics over http://cdn...xxx. This is unfortunately very inconvenient for visitors when the "unsecured icon" appears in the browser. I have only been able to track it there up to this point, I don't know if the certificate error occurs elsewhere as well.

**Comment by Renebr02** [comment]
Ok, it looks like this is just an nginx configuration issue on my end. (header connectrion upgrade). Was just confused because it is the same on app.coracle.social.

**Comment by Renebr02** [comment]
Rejoiced too soon. Unfortunately, it still happens under micro-apps.

**Comment by staab** [comment]
Hmm I recently fixed something related to this (by adding an imgproxy option to settings). Can you try adding that and let me know if it solves the issue? Otherwise it could be a fetch against an insecure nip05, which I plan on proxying eventually, see #81. Closing this for now.
