### ISSUE TITLE
Fix instructions about env.local

### ISSUE THREAD

**Issue by dtonon** [coracle-social/coracle#141]
The [README](https://github.com/coracle-social/coracle/blob/master/README.md) says:

> Add an env file from the template: cp env.template env.local

But `env.template` does not exist.

The local env runs just fine without `env.local`, and the env variables seem optional:

<img width="669" alt="image" src="https://github.com/coracle-social/coracle/assets/89577423/539e0bfd-3650-4761-9a0d-3ebe639a9b4a">

**Comment by staab** [comment]
Fixed in 7ca57ae96168be758e6f447706d8a023c7efe11f
