### ISSUE TITLE
Unable to access profile's details

### ISSUE THREAD

**Issue by dtonon** [coracle-social/coracle#143]
Sometimes (~50%) clicking on the "Details" link does nothing.
No error messages in the dev console.

<img width="737" alt="image" src="https://github.com/coracle-social/coracle/assets/89577423/25ff933a-c216-450c-8516-cf504b9a4f10">

**Comment by staab** [comment]
Is this on a dev build? Svelte has really weird bugs like this sometimes, try restarting the dev server and refreshing if so.

**Comment by dtonon** [comment]
Sorry I forgot the env, I'm talking about the production: https://coracle.social
The problem persists even if I force a reload.

**Comment by staab** [comment]
Got it, was able to reproduce, fixed on master.
