### ISSUE TITLE
bug: Event ID button doest switch between hex and note id 

### ISSUE THREAD

**Issue by shaibearary** [coracle-social/coracle#146]
![image](https://github.com/coracle-social/coracle/assets/26760878/c2211d4b-4d8f-4b9e-9762-48724cf31d81)
not sure if anyone noticed it already but , i can only copy hex now

**Comment by shaibearary** [comment]
here is the video
https://github.com/coracle-social/coracle/assets/26760878/b23ef729-6120-4620-92ee-c356fc2280df

**Comment by staab** [comment]
Thanks! Fixed on master.
