### ISSUE TITLE
Generalize nsec bunker to nostr connect

### ISSUE THREAD

**Issue by staab** [coracle-social/coracle#147]

**Comment by manimejia** [comment]
Imma dive into this once I get oriented to coracle with #167.

**Comment by staab** [comment]
Great. I think I've mentioned it, but I would really like to see a OAuth workflow for this. That way, clients wouldn't have to build the admin in, key management could happen elsewhere.

So:

- Log in > Log in with key/identity provider
- Ask for a url, or look up the correct provider somehow (like how bitwarden asks what server you want to connect to)
- Initialize OAuth workflow, pass scopes and client id etc over to the auth provider
- Approve/deny scopes
- Redirect to app with nsec bunker token

Bam, very familiar auth workflow for end users, using nsec bunker.
