### ISSUE TITLE
Add context to long-form note replies

### ISSUE THREAD

**Issue by fr4nzap** [coracle-social/coracle#158]
I replied to https://habla.news/verbiricha/splits on Habla.news

But my kind 1 note appeared on Coracle without context. It's confusing!

![](https://image.nostr.build/e5e7a0a85a16a07e47ec9b3cc0d2189ba81c1d935ee38e9e5cc61ffe31314000.png)

Please show that it was a reply to an article! We chatted about this not long ago @staab

**Comment by staab** [comment]
Thanks, this will be fixed in the next release.
