### ISSUE TITLE
Not possible to scroll to see the message I'm typing 

### ISSUE THREAD

**Issue by bitcoinuser** [coracle-social/coracle#163]
Hi, 

Not possible to scroll to see the message I'm typing.

https://github.com/coracle-social/coracle/assets/1178856/cdc10df4-0870-49cd-b2f8-3c679491a956

**Comment by bitcoinuser** [comment]
Same things on DM's

**Comment by staab** [comment]
I can't replicate this on android, is this iOS Safari?
