### ISSUE TITLE
Improve mentions

### ISSUE THREAD

**Issue by Giszmo** [coracle-social/coracle#166]
As Coracle supports editing the mentions:
Average Joe has no clue about the difference between
* `@<somebody>`: somebody gets mentioned in a p-tag, triggering a notification
* `nostr:<somebody's npub>`: somebody only gets mentioned in the body of the text but not in a p-tag, avoiding a notification
* `nostr:<somebody's npub>` plus p-tag: Some advocate for this approach to not use different formats in the content

Coracle already lists the p-tag mentions resulting from the thread, allowing the user to delete them but there are issues:
* the user cannot add p-tag mentions. For example if he decided to remove some from the list, he can't add them back.
* the user can't reference profiles without notifications easily

I suggest to

* add profiles to the mentions-box as the user mentions them using the "@" syntax
* show each mention with a :speaker: symbol instead of the :x:
* clicking the :speaker: turns it into :mute: (and puts it to the end of the list, so the user can quickly mute many without moving the mouse)
* user can enter further mentions in the mentions box that get added via p-tags without being referenced in the text

**Comment by staab** [comment]
I think it's ok as is. Coracle converts inline npubs to `p` tags anyhow following approach #3, so use case #2 isn't supported. So if someone wants to mention someone they can just @ them at the bottom of the note, which is idomatic. Maybe @dtonon disagress, but I think this is ok.

**Comment by dtonon** [comment]
I agree with @staab, the average Joe mentions using @, so it should not be worried by any other format.

Adding the possibility to notify without a visible mention doesn't seem so useful, for the mentioned user can be counter intuitive (he cannot see himself in the message) and it's prone to spam behaviours.

But I agree that the the removal interface can be improved a little with a toggle style, to permit adding back an user removed by error. @Giszmo UX specs for this are ok.
