### ISSUE TITLE
Clicking the "Open an Issue" button fails to open github

### ISSUE THREAD

**Issue by Ademan** [coracle-social/coracle#176]
Running coracle via https://app.coracle.social/ in Chromium Version 118.0.5993.70 (Official Build) snap (64-bit) on a desktop, clicking on "About" in the sidebar then "Open an Issue" navigates the browser to `https://app.coracle.social/https://github.com/coracle-social/coracle/issues/new` which is surely not intended, and displays a page saying:

> Sorry, we weren't able to find "https:".

**Comment by staab** [comment]
Thanks, will be fixed shortly
