### ISSUE TITLE
Integrate nostrcheck.me

### ISSUE THREAD

**Issue by staab** [coracle-social/coracle#181]
- [ ] Allow the user to pick which upload service to use in settings
- [ ] Show the upload service being used in the upload dialog
- [ ] Handle errors properly

**Comment by quentintaranpino** [comment]
I'm going to try 🙂

**Comment by quentintaranpino** [comment]
> * [X ]  Allow the user to pick which upload service to use in settings
> * [ ]  Show the upload service being used in the upload dialog
> * [X ]  Handle errors properly

https://github.com/coracle-social/coracle/pull/182

**Comment by quentintaranpino** [comment]
> > * [x]   Allow the user to pick which upload service to use in settings
> > * [x]   Show the upload service being used in the upload dialog
> > * [x]   Handle errors properly
> 
> #182 😊

(I had forgotten it)

**Comment by staab** [comment]
This is done, @quentintaranpino thanks for your help!
