### ISSUE TITLE
Component library

### ISSUE THREAD

**Issue by manimejia** [coracle-social/coracle#186]
Who wants to design, code, and maintain their own hand rolled set of UI components, when plenty of component libraries are already available to do it for free?

Here's one:
https://framework7.io/

Refactoring existing (hand rolled) UI elements in coracle to use such a library will take time, and should be approached incrementally.  The result WILL change the look and feel of the coracle user experience. But the benefits will be immediately noticed, in "out of the box" improvements to mobile touch, a11y accessibility, standardized UX feel, usage documentation, and many many more components to choose from in building out UIs.

**Comment by manimejia** [comment]
putting a pin on this.

**Comment by staab** [comment]
Framework looks really good. I'm generally a "libraries not frameworks" kind of guy and prefer to roll my own, since frameworks come with a lot of bloat and opinions. But this might be worth doing as we move towards actual apps. DaisyUI is also very nice, and tailwind-friendly.

**Comment by manimejia** [comment]
Yes. There are valid arguments for having both simple and more complex dependencies. UI component libraries (and their css styles, and icons, and accessible controllers, other baggage that make up a "framework") are best left to grow big and full of "usable components" IMHO ... pending they are secure, stable, and well supported. 

So i will take your lead as to picking the "right" framework to use, as I am brand new to the world of svelte apps (and ts for that matter) and what's available. But I will happily put time in to refactor the coracle UI bit by bit. In fact... I'm looking forward to it TBH.

**Comment by staab** [comment]
Tailwind-compatible options:

- https://ui.shadcn.com/examples/playground
- https://daisyui.com/
