### ISSUE TITLE
feedback tab empty

### ISSUE THREAD

**Issue by matata2140** [coracle-social/coracle#187]
<img width="897" alt="Schermafbeelding 2023-10-29 om 00 29 19" src="https://github.com/coracle-social/coracle/assets/127629040/e840c643-5c04-4930-b610-b3a1aaa23397">

**Comment by staab** [comment]
Thanks, fixed in the next release

**Comment by matata2140** [comment]
oh just reading this lol - ignore pr (was mainly just practicing making pr's)
