### ISSUE TITLE
Some links in notes point to coracle instead of their final target

### ISSUE THREAD

**Issue by Ademan** [coracle-social/coracle#191]
Using app.coracle.social in Chromium Version 118.0.5993.117 (Official Build) snap (64-bit) if you view [this note](https://app.coracle.social/notes/nevent1qqsrrg8jrp0hupmcggm430854gst7uhkwx0wpnvgaxygqxtegscn2xgpz3mhxue69uhhyetvv9ujuerpd46hxtnfduq3yamnwvaz7tm0venxx6rpd9hzuur4vgqs6amnwvaz7tmwdaejumr0dsq3wamnwvaz7tmjv4kxz7fwvd6hyun9de6zuenedyq3vamnwvaz7tmjv4kxz7fwdehhxarj9e3xzmnyqyd8wumn8ghj7un9d3shjtn0wfskuem9wp5kcmpwv3jhvqgjwaehxw309ac82unsd3jhqct89ejhxqgnwaehxw309aex2mrp09skymr99ehhyecpzpmhxue69uhkummnw3ezuamfdejsef55mr) the last link, to test_keys.txt points to within coracle to `https://app.coracle.social/media/https%3A%2F%2Fgithub.com%2FAdeman%2Frust-musig-psbt%2Fblob%2Fwip%2Ftest_keys.txt` rather than out to github. If you click the link, it will open a new pane within coracle, which you can click to take you to the real link target.

Note the `/media/` portion of the URL, probably hinting at what is causing this. I suppose it may be impractical to fix if it's part of a larger remote media handling strategy.

**Comment by staab** [comment]
This is deliberate, but cmd+click was opening Coracle's pane, which seems unnecessary. The href is now the canonical one, and the click handler is overridden in no-media mode.
