### ISSUE TITLE
Add local relays for Thai users

### ISSUE THREAD

**Issue by alltheseas** [coracle-social/coracle#202]
## user story

As a first time Thai nostr user onboarding to Coracle, I would like to have the Thai relay(s) included in the Coracle bootstrap relay list, so that I can jump into discussions in Thai.

### acceptance criteria

1. Thai users automatically have Thai relay(s) included on their bootstrap list

### community sourced relay list

🇹🇭 Relay List

wss://relay.siamstr.com
wss://relay.zerosatoshi.xyz
wss://th2.nostr.earnkrub.xyz
wss://teemie1-relay.duckdns.org

https://damus.io/note1gx49ruq0p7z8pvfaee07nneymuq4pcjeljwzk5xkaaltsg6z6dms3ppc8l

### implementation suggestion

On iOS There's a explicit signal, which is the same one that's used by the auto translations feature: using the list of preferred languages from iOS settings.

### benefit

Engage, and increase Thai Coracle user retention

### comment

Damus implemented this feature for Japanese users, based on Nostrasia feedback. https://github.com/damus-io/damus/issues/1447#issuecomment-1773051710

**Comment by staab** [comment]
Coracle runs off of nostr.watch's relays.json list, but unfortunately it doesn't seem to be up-to-date. I'll look into fixing this.
