### ISSUE TITLE
Feed items displayed out of order

### ISSUE THREAD

**Issue by DireMunchkin** [coracle-social/coracle#212]
When more posts are loaded in via infinite scroll, sometimes there randomly seems to be very old posts in the feed, or replies even though I've unchecked show replies.

For example this screenshot was captured Dec 19 and has a reply and a post from Nov 27th:

![Capture](https://github.com/coracle-social/coracle/assets/1665676/29b854a4-439a-470a-aece-c1b084302db7)

**Comment by staab** [comment]
This is a known issue, and is a result of the complexity involved in pulling events from multiple relays in a way that is complete, ordered, and fast. I'm constantly improving the algorithm, so I'll close this and continue to look for ways to improve things.
