### ISSUE TITLE
Request: Add a button on user profiles to "mention" them

### ISSUE THREAD

**Issue by Ademan** [coracle-social/coracle#216]
If I am on a user profile, and I want to create a public post mentioning them, I have to go back to the main page and create a new note, then search for their user. It would be a convenient shortcut if there was a button on user profiles that opened a new note pre-populated with the user's info.

This is doubly nice on nostr where user names are not guaranteed to be unique, and there can be some ambiguity in searching for them.

Twitter implements this by always having the "new note" button (Labeled "Post") visible, and contextually, if you are on a user profile, when you click the "Post" button it will pre-populate that user into the text box.

![2023-12-21-131136_846x754_scrot](https://github.com/coracle-social/coracle/assets/18740/5f04ce77-fbd9-40d0-8c9d-b8ff736c0254)

Pleroma's Soapbox frontend (fediverse) implements this as an "@ Mention" button in the context menu on user profiles.

![2023-12-21-130621_610x776_scrot](https://github.com/coracle-social/coracle/assets/18740/27d6e333-ff82-4075-b436-6ee08393cbb3)

**Comment by staab** [comment]
Fixed in 8fba7b2
