### ISSUE TITLE
Hell threads

### ISSUE THREAD

**Issue by DireMunchkin** [coracle-social/coracle#217]
I got tagged in some sort of long lived hell thread and I'm still getting notifications from this like months later. Please consider being more restrictive in showing notifications.

Specifically, don't show every reply from a thread you participated in or where tagged on as a new notification. This just makes it trivial to grief people. Just direct replies to your post and @-ing.

**Comment by staab** [comment]
It seems better to selectively opt-out rather than never show deep threads. Have you tried muting the root note of the conversation? Not all clients do it, but most will tag the root of the conversation (you may have to mute multiple "roots" because some clients are buggy). Coracle ignores children of muted notes. Give that a try and let me know how it works.

**Comment by DireMunchkin** [comment]
Hello, thanks for taking a look at it. AFAICT this is not what happens? See screenshot, I still get notifications to replies I've muted,

![Screenshot from 2024-01-23 23-24-18](https://github.com/coracle-social/coracle/assets/1665676/2e3f4941-61c6-44e8-9bf3-3232fbc9b02d)

In any case this thread is extremely long so you can't even load the root post. Maybe I'm missing something, but I.E here's a [link](https://coracle.social/notes/nevent1qyt8wumn8ghj7cn9wehjumn0wd68yvfwvdhk6tcpramhxue69uhkummnw3ez6vpj9ejx7unpveskxar0wfujummjvuhszrnhwden5te0dehhxtnvdakz7qghwaehxw309aex2mrp0yhxummnw3ezucnpdejz7qgmwaehxw309aex2mrp0yhxummnw3exjcmgv4ejummjvuhszxrhwden5te0wfjkccte9e3h2unjv4h8gtnx095j7qg4waehxw309aex2mrp0yhxgctdw4eju6t09uq3jamnwvaz7tmjv4kxz7fwwdhx7un59eek7cmfv9kz7qgawaehxw309ahx7um5wgknqvfw09skk6tgdahxuefwvdhk6tcprfmhxue69uhkummnw3ezuargv4ekzmt9vdshgtnfduhsqg8xy0w90xd7l43fwytk8tgku5hyw4kx0zpt638xk9z2dt5awazzvqdqme7p) to an event in the hell thread. You can either go one level up (takes forever) or view thread (times out),

**Comment by DireMunchkin** [comment]
Update: I muted 5-7 more people and now I managed to clear up my notifications. Still a bit annoying to get tagged in one of these, but it was doable after all. I think I can be happy with that.

**Comment by staab** [comment]
Glad you got it figured out, I tested this behavior earlier today and it worked for me — I'm not sure why it's showing for you in the screenshot there. At any rate, thanks for reporting, I'll have my eyes open for this in the future.

**Comment by DireMunchkin** [comment]
So I took another look at Coracle with the recent release and I had like 30 notifications, all of which are people using the hell thread as a chat room.

Could you consider maybe removing the notification on replies to notes you were mentioned in? I doubt I can use this client otherwise.

**Comment by staab** [comment]
Hey, thanks for mentioning this again, it looks like the note mute behavior was broken. I've release a fix for that. In theory, if you mute the root note for the hell thread, you won't be notified about replies to it — this relies on the clients producing those notes tagging the root note though, there's no way to defend against hell-thread air replies. But it doesn't sound like you have that particular problem, so this should fix it for you. The note mute button is in the note overflow menu.

**Comment by DireMunchkin** [comment]
This is how my notifications look:
![Peek 2024-09-19 18-55](https://github.com/user-attachments/assets/e858aff8-5339-4c1a-8106-452dff2597f5)

As I hope it's apparent I can't possibly mute the root of this mess or everyone talking in it. The oldest notifications don't even load.

**Comment by staab** [comment]
Can you try hard-refreshing? Those shouldn't be showing up anymore after the latest update

**Comment by staab** [comment]
Awesome, glad that worked!

**Comment by DireMunchkin** [comment]
I had a look at the client this morning and all the notes I muted are back 😔

I also notice that Coracle only seems to mute direct replies to the note I muted, not 3-4 or more levels of nested replies. This means it takes me around 20 minutes to mute all of these.

You publish the note mutes to the relays right? Could this be some sort of data persistence issue?

If you could fix so that ALL nested replies to a note are muted, not just the first tree level that'd be great because then I could more efficiently leave this thread.

**Comment by DireMunchkin** [comment]
I figured out the problem - Apparently when I mute a user in Primal, the note mute list in Coracle is reset. I'll add a report to https://github.com/nostrability/nostrability

**Comment by staab** [comment]
> I also notice that Coracle only seems to mute direct replies to the note I muted, not 3-4 or more levels of nested replies.

I imagine this has something to do with the client someone is using to publish notes with, which isn't preserving the root tag. I could potentially recursively fetch context and mute based on that, but it would be a lot of work to support an incorrect implementation.

**Comment by DireMunchkin** [comment]
OK makes sense - As long as I don't get my mute list cleared by that Primal issue it's not so bad.
