### ISSUE TITLE
allow direct url links to notes and rooms without login redirect

### ISSUE THREAD

**Issue by brenzi** [coracle-social/coracle#22]
I'd like to link directly to a note or a public channel with an url like:

https://coracle.social/chat/note18kst54gwje8n5t3cfpdud4duwh37wtfu4zpefd6a6q24nc2uecqs6vy8lq
and the official encoding:
https://coracle.social/chat/nchannel1qqsrmg96258fvne69cuysk7x6k78tcl895723qu5kawaq92eu9wvuqgthxzyq

or 

https://coracle.social/notes/note17vkkaqz5mn8wcl76lqf2y4jc98dkhw86xrz8nrj2k6wjkcd54zvsngmqc3

Now this does not seem to work because I'm redirected to the login page. I think it makes more sense to first show the content that the url requests and a allow read-only without disturbance

**Comment by staab** [comment]
This should be fixed in the next version.
