### ISSUE TITLE
Issue with login to wine relay in coracle, but not in other clients

### ISSUE THREAD

**Issue by theerror** [coracle-social/coracle#230]
I do have some strange issue, that I'm not able to login to filter.nostr.wine relay in Coracle (it says "logging in"). 
<img width="673" alt="image" src="https://github.com/coracle-social/coracle/assets/4508328/a3e1e731-d853-4672-8f39-31e416df42fe">

[Based on this](https://docs.nostr.wine/filter/readme), they should support NIP-42
> We now support both NIP-42 (client authentication) and NIP-50 (search) on filter.nostr.wine. If your client supports NIP-42 you can connect directly to wss://filter.nostr.wine without using the /npub addition. 

and I do not have any issue with other client like Amethist or Primal (web), just Coracle. 

As workaround I'm using npub and this is working fine. 

Any idea what I can check? Coracle should support NIP-42, right?

**Comment by staab** [comment]
By default Coracle doesn't authenticate with relays to protect your privacy. You can turn this on in settings. The design could be improved to make that clearer.
