### ISSUE TITLE
Firefox on Ubuntu 22.04 /settings/keys error

### ISSUE THREAD

**Issue by EthnTuttle** [coracle-social/coracle#234]
![Screenshot from 2024-01-15 15-15-26](https://github.com/coracle-social/coracle/assets/133234413/cdcb92e0-906b-4ec0-821c-a82d60fff633)
[console-export-2024-1-15_15-17-17.txt](https://github.com/coracle-social/coracle/files/13942755/console-export-2024-1-15_15-17-17.txt)
![Screenshot from 2024-01-15 15-18-12](https://github.com/coracle-social/coracle/assets/133234413/2b8c4a50-10e6-4ba1-a2c3-c5821ea292a1)

**Comment by staab** [comment]
Closing until I have more information.
