### ISSUE TITLE
Improve submission status for new responses

### ISSUE THREAD

**Issue by dtonon** [coracle-social/coracle#235]
Following up #233 (_Replies don't show up immediately_) I propose a new UI to show the posting/posted status of a note.
The note is placed in the correct position on the thread and the bottom bar is replaced with a loading animated component:

<img width="767" alt="Screenshot 2024-01-15 alle 21 16 21" src="https://github.com/coracle-social/coracle/assets/89577423/ac54786b-2dcb-47d8-afc8-05c7ad48742f">
<br/><br/>

After the submission procedure ends the summary is displayed on the same bar, on the left a buttons permit to see the details (current bottom sheet modal):

<img width="768" alt="Screenshot 2024-01-15 alle 21 23 03" src="https://github.com/coracle-social/coracle/assets/89577423/6295a3c0-045f-4731-a4e3-aa81d547c7de">
<br/><br/>

The bar can be replaced after a certain amount of time (ex. 30 seconds) or if the note receives an event (reply, reaction, zap).

**Comment by dtonon** [comment]
We should probably add the case of an unsuccessful submission (e.g. network error) or one with a high percentage of missing relays, giving the user the option of retrying the submission with a click.

**Comment by ticruz38** [comment]
> We should probably add the case of an unsuccessful submission (e.g. network error) or one with a high percentage of missing relays, giving the user the option of retrying the submission with a click.

@hodlbod ? Reopening this issue if the retry is necessary

**Comment by staab** [comment]
I think it's ok for now, we could probably improve the HUD before adding inline retry
