### ISSUE TITLE
Wrong npub rendering in profile's about

### ISSUE THREAD

**Issue by dtonon** [coracle-social/coracle#236]
https://coracle.social/nprofile1qqs0nht2wcjsvfst8z3d8ed5vssnctj8lgu8ws5la8hxpcr35vdq04cprpmhxue69uhkv6tpw34xze3wdehhxarjxyhxxmmdqyf8wumn8ghj7ur4wfcxcetsv9njuetn6v5mmj

npub12hcytyr8fumy3axde8wgeced523gyp6v6zczqktwuqeaztfc2xzsz3rdp4 is rendered as "htlc_nbot" while should be "NoGood".

Original event: https://njump.me/nevent1qqsr3w3d0e6qu3e663dufq62crlgveyx5zvwfv5xxjzzjrc4a3flphqn4kkzz

<img width="718" alt="image" src="https://github.com/coracle-social/coracle/assets/89577423/45eb2a6a-2293-4088-bc7d-e870db504464">

**Comment by staab** [comment]
Fixed by eb6f20fd7610d150bb1b59b148ca25644e5d4ba6
