### ISSUE TITLE
Add support for Nostr Connect

### ISSUE THREAD

**Issue by tiero** [coracle-social/coracle#24]
Would be useful to have Coracle support NIP46 Nostr Connect remote signers.

https://github.com/nostr-protocol/nips/pull/153

**Comment by devsou-com** [comment]
That would be nice!

**Comment by manimejia** [comment]
Preliminary work has been done already to "connect" using nsecbunker. Working on generalizing this to a NIP-46 client implementation.  (See #147)

Wd be nice to use the nostr-connect library ... 

https://github.com/nostr-connect/connect

Difficult to test without a NIP-46  key storage implementation (that works, lol) Wondering if there are any more open spots to beta test Nostrum native app? @tiero 

https://github.com/nostr-connect/nostrum

**Comment by staab** [comment]
Cool, I didn't know about nostr-connect, that could be good. Right now I use NDK, but that's the only feature that depends on it. Removing NDK as a dependency would be nice.

**Comment by staab** [comment]
There's also https://github.com/erskingardner/nostr-ignition
