### ISSUE TITLE
Onboarding: Follow all suggested profiles 

### ISSUE THREAD

**Issue by alltheseas** [coracle-social/coracle#241]
_what happens_

During onboarding, Coracle suggests individual profiles to follow. I can individually click "Follow" on each one. 

_suggestion_

Add "Follow All" button, so user doesn't have to click 'Follow' a dozen times. Consider adding tooltip or friendly text explainer "you can always unfollow at any point in time".

_rationale_

I've seen feedback that it's tough finding real people in the beginning. Reducing friction on adding people to the seed follow list will help a bit with this problem. Conversely, I have never heard feedback "you are suggesting too many follows" during onboarding. 

![Screenshot 2024-01-22 at 1 42 56 PM](https://github.com/coracle-social/coracle/assets/64376233/c8e64bcd-a031-48d9-be35-d41f2b90f1f1)

**Comment by alltheseas** [comment]
Mock
![yolofollow](https://github.com/coracle-social/coracle/assets/64376233/2b232bf4-6a13-4daa-805c-815781067a37)

**Comment by alltheseas** [comment]
Can confirm I clicked on the individual follow button for 30 seconds with no end in sight 😅

**Comment by staab** [comment]
I'm going to approach this differently, with some kind of topical or structured follow, rather than a static list. Follow all will hopefully be part of that.

**Comment by alltheseas** [comment]
Check out the Damus one - it is topic themed.

**Comment by staab** [comment]
I added friction instead, but I like it

**Comment by alltheseas** [comment]
I like the new topical groupings, nice!

I still think many, if not most new folks would not want to follow 2/7 e.g. Christians if they are interested in Christianity, but all people in that group.

**Comment by staab** [comment]
That's a supet good point.

**Comment by alltheseas** [comment]
I can follow entire categorized groups now - nice!
