### ISSUE TITLE
Onboarding limbo unhappy path

### ISSUE THREAD

**Issue by alltheseas** [coracle-social/coracle#242]
_what happens_

After "account" creation, and follow screen I did not see a "continue" button. Instead I clicked on a "X" button in the top right.

This appears to cancel account creation, and take me to a Coracle landing page in the logged out view. 

If I attempt to paste the nsec, I am thrown into some incorrect setup / profile recovery screen.

This is a unhappy onboarding path. 

_suggestion_

1) Consider making "continue" button ever present during selecting follows during onboarding.
2) Consider what the need is to keep the "X" button during selecting follows during onboarding. Consider removing, or adding some warning (e.g. "Warning, if you leave the process now you will have to start over again/your profile will not be setup correctly")

**Comment by alltheseas** [comment]
![nocontinue](https://github.com/coracle-social/coracle/assets/64376233/bca534df-3ba9-43d8-abeb-7f97a01efd71)

**Comment by alltheseas** [comment]
### mockup

![mockup continue](https://github.com/coracle-social/coracle/assets/64376233/8bdab002-b372-4aa7-9a13-9aec264e11a0)

**Comment by staab** [comment]
Definitely hoping to re-work onboarding in the next week or two, I'll keep this in mind.
