### ISSUE TITLE
Add Zaps

### ISSUE THREAD

**Issue by staab** [coracle-social/coracle#25]

**Comment by predatorprasad** [comment]
Can you please elaborate on this

**Comment by staab** [comment]
Following the NIP here: https://github.com/nostr-protocol/nips/blob/master/57.md

This probably won't be too much more involved than reactions.

- Add a zap button to the right of like/flag in Note.svelte
- When the button is clicked, I'm not exactly sure what to do, but maybe call a handler for a link type, delegate to a wallet implementation, or just show a qr code in a modal dialog
- Show total zap amount on a given note, be sure to verify zaps as completely as we're able. This data should probably be requested in `streamContext`.
- Add a default zap amount in settings

Be sure to work off of/merge into the dev branch.
