### ISSUE TITLE
Fix npub formatting, add copy npub ez button in profile view

### ISSUE THREAD

**Issue by alltheseas** [coracle-social/coracle#256]
_what happens_

npub is cutoff in coracle profile view

![Screenshot 2024-01-31 at 9 27 01 AM](https://github.com/coracle-social/coracle/assets/64376233/2e14fc15-6722-4f84-ad8f-a77bacedf057)

_suggestion_

1) show full npub in one or more lines depending on browser size (do not cut off)
2) bonus points: add copy npub button for ez access immediately adjacent to npub

**Comment by staab** [comment]
This has been reformatted to include an ellipsis, but adding a copy icon to the right of the npub (with a toast to indicate success) would be good.
