### ISSUE TITLE
Relays in follow people prompt during onboarding

### ISSUE THREAD

**Issue by alltheseas** [coracle-social/coracle#271]
Not sure if this is with intent, or by design.

When I tap on in bottom right of suggested people onboarding screen on

"`View selections`" 

![Screenshot 2024-02-09 at 4 14 29 PM](https://github.com/coracle-social/coracle/assets/64376233/f906c129-08ea-414a-ac4c-7df608a16784)

The concept of relays is introduced in the follow people phase 

![Screenshot 2024-02-09 at 4 14 33 PM](https://github.com/coracle-social/coracle/assets/64376233/25c87637-92bb-426c-9ac9-ce80ca9f1010)

Do you select relays, by virtue of who you just followed?

If so, nice!

**Comment by staab** [comment]
I considered it, but skipped it for the moment. I will likely add that though, it's just hard to know if a given user can write an an arbitrary relay.

**Comment by staab** [comment]
Fixed by 1dc23cedc4752f5a21e692f8d5b548ad407a05c0
