### ISSUE TITLE
Groups show name on other platforms as a number and other groups parsing issues on coracle

### ISSUE THREAD

**Issue by joshgaskin** [coracle-social/coracle#279]
I've checked out several other platforms and it seems the name of groups isn't following the NIP. 

I created this group on coracle: https://coracle.social/groups/naddr1qvzqqqyx7cpzp4q7xsdz6p636akhnafg9yru265l572nerhyqzhxeuu8waej8nfaqqgnxvfn8ymnjd3kxs6ngwpjxvergdgz3jre7/notes

the name seems to consistently show as this number which is a d tag:
![image](https://github.com/coracle-social/coracle/assets/94354171/e86cbda0-a4e2-4e07-9d59-0d72c5ad022c)

When I try to reference the group on coracle, it shows like this:
![image](https://github.com/coracle-social/coracle/assets/94354171/a94fd78b-17a0-4592-b2a7-648798858a91)

**Comment by staab** [comment]
Just pushed an update that fixes the rendering within quotes. For the name, I'm optimistically using the `title` tag described in https://github.com/nostr-protocol/nips/pull/1024, which makes it possible to rename a group. This also avoids conditions where a user intends to create a new group, and instead updates an old group with the same name. What client are you looking at there?
