### ISSUE TITLE
Double down arrow onboarding abrupt cancellation 

### ISSUE THREAD

**Issue by alltheseas** [coracle-social/coracle#282]
_what happens_

During onboarding, when I tap on the double down arrow when choosing follows, I am led to the feed in a logged out state. There is no trace that onboarding started.

_what I expect to happen_

When I tap on the double down arrow, I expect to simply return to the onboarding themed group screen (and not cancel my onboarding/new key creation)

Screencap:

![Screenshot 2024-02-15 at 8 13 26 PM](https://github.com/coracle-social/coracle/assets/64376233/39abff2b-2342-41a3-b2f8-19e107336871)

**Comment by staab** [comment]
Fixed in the next version
