### ISSUE TITLE
Problem on load parent posts

### ISSUE THREAD

**Issue by projetos** [coracle-social/coracle#284]
![Screenshot from 2024-02-21 13-22-44](https://github.com/coracle-social/coracle/assets/2190909/45a29da4-3b07-44cc-9d5e-4ba25bf0b1fd)

Loading infinitely

**Comment by staab** [comment]
This is more of a problem with the client that published the note, since it didn't provide any relay hints. But I do want to handle this scenario, next release will try harder to infer hints for replies.

**Comment by staab** [comment]
cf5cf2f1b9258d0a3f9ed9c1cb488bec868fff30
