### ISSUE TITLE
Add private relay

### ISSUE THREAD

**Issue by kornpow** [coracle-social/coracle#316]
I am trying to add my private relay, which I am currently using Bostr.

As far as I can tell from using the interface, I cannot add a relay which is not in the list provided by the UI.

**Comment by staab** [comment]
You can do this under "Browse relays" by typing in your relay url and hitting join in the list below. But I agree it could be clearer.

![Screenshot 2024-03-21 at 1 40 34 PM](https://github.com/coracle-social/coracle/assets/2494842/05aca81f-2d83-4b75-a157-632ebd2e1b72)

**Comment by kornpow** [comment]
Im also trying to connect to a ws:// relay, which I am running locally, for testing, and it doesnt connect when I do it how you showed me. My guess is since it doesnt specify, then it just defaults to wss://. It does work on damus, and I do have to specify ws://.

**Comment by staab** [comment]
Yeah, ws:// is unfortunately not going to work since browsers don't support connecting to insecure contexts from secure ones.

**Comment by kornpow** [comment]
ok. I will just have to properly deploy my Bostr relay then!

**Comment by staab** [comment]
You can also use something like ngrok to host it locally but get a ssl-enabled domain name.
