### ISSUE TITLE
Coracle Social is nagging me to sign a kind 15 event

### ISSUE THREAD

**Issue by vicariousdrama** [coracle-social/coracle#318]
I don't know what a kind 15 event is, but the application is persistently requesting that I sign a kind 15 event, for which I'm denying

![image](https://github.com/coracle-social/coracle/assets/88121568/84d43bfa-8cc9-42a2-a678-b7cb2b692bc8)

The details are a lot of event ids.

**Comment by staab** [comment]
Kind 15 is for read status: https://github.com/nostr-protocol/nips/pull/933

The only way to make this kind of bookkeeping state interoperable is to publish it as nostr events, which triggers this kind of opaque dialog. That basically makes it impossible to micromanage permissions, so for now at least users will just have to trust Coracle to do the right thing.

**Comment by vicariousdrama** [comment]
ok. I'll refocus efforts on the NIP07 extension makers to add some support like `Deny` in addition to the cancel and confirm choices that Alby presents.  I haven't yet looked at how nos2x handles requests but its been a thorn to not be able to always ignore such requests when they come in.

**Comment by staab** [comment]
I've temporarily disabled kind 15, so this one is closed until I figure out what I'm going to do about read receipts.
