### ISSUE TITLE
Coracle not parsing NIP-46 `connect` "error" response as expected

### ISSUE THREAD

**Issue by bu5hm4nn** [coracle-social/coracle#320]
#### What happened
As mentioned on https://github.com/nostrability/nostrability/issues/25, coracle (as of right now on coracle.social) does not pass the _secret_ as second parameter on connect.

However what I am reporting here is that despite the connect failing, coracle pretended that the login succeeded and displayed a success message and went on to show my account as logged in.

The content of the `24133` from gossip was:
```{"error":"connect requires two parameters","id":"56vzv7l","result":""}```

On success gossip would have returned 
```{"error":"","id":"56vzv7l","result":"ack"}```

#### What I expected to happen
I expected an error message from Coracle that displays the returned error string `"connect requires two parameters"`. While seeing this string would not help a user, it would greatly help debugging app-interoperability if a user included it in their bug report.

**Comment by staab** [comment]
I believe this was fixed by #321
