### ISSUE TITLE
Group creation without feedback resulting accidental multiple group creation

### ISSUE THREAD

**Issue by eapo** [coracle-social/coracle#326]
On Android Brave browser After pressing "[Create open group](https://coracle.social/groups/new)" wasn't any feedback, did some changes, pressing 3 more times, resulted 4 different "Szeklerland" group:

![Screenshot_20240331-153601_Brave](https://github.com/coracle-social/coracle/assets/4000929/72f0017e-bbca-4fa5-bc42-2c117a013421)

It is possible to destroy them?

**Comment by staab** [comment]
Thanks, I'll fix this. In the meantime, you can delete groups using the overflow menu:

![Screenshot 2024-04-01 at 2 17 28 PM](https://github.com/coracle-social/coracle/assets/2494842/d08bd2a4-a142-4ddb-86da-48ad88c5941d)
