### ISSUE TITLE
Coracle strips hashes from links, markdown support breaks with links

### ISSUE THREAD

**Issue by dskvr** [coracle-social/coracle#335]
The inconsistencies here cause some confusion and require that I check the event json to see if the note was altered pre-publish or if it is a rendering issue. 

- Sharing a hashed link, for example a github link with line numbers, is stripped `nostr:nevent1qywhwumn8ghj7mr4de3kscn00qh8xctwv3mkjcmg9enxzund9uq32amnwvaz7tmjv4kxz7fwv3sk6atn9e5k7tcpzdmhxue69uhhqatjwpkx2urpvuhx2ue0qqsy96802f55pn634vtgzvnvva0pcj8cq8a4jej2quyf4vl7295wcxcddv7qj`
- Sharing a single-backticked link for instance, is rendered poorly, resulting in a bad location change `nostr:nevent1qyf8wumn8ghj7mn0wd68yat99e3k7mf0qyg8wumn8ghj7cfwdehhxtnvdakz7qghwaehxw309aex2mrp0yhxummnw3ezucnpdejz7qpqx56znkn94uhgs7qxeg5cr0ph0lw3rev0aps0lawhglcm4wxyunvsy0qv79`

**Comment by staab** [comment]
Fixed in the next release
