### ISSUE TITLE
Can't access my Group

### ISSUE THREAD

**Issue by lupus84** [coracle-social/coracle#340]
Hey Guys,
I made a group with my account and now I can't get access to my own group.
Can you help? 
Cheers

**Comment by staab** [comment]
Did you change relays recently? Coracle sends your admin key to you via an encrypted event in the background. If this event gets lost, logging in on a new device (or after a log out) will fail to find that event, which means you won't be able to administer or get access to the group. You can also back up your admin keys manually from the Keys page.

**Comment by lupus84** [comment]
Where can I login with my admin key?

**Comment by staab** [comment]
Ok, just pushed an update that will allow you to import your admin key into your Keys settings page.
