### ISSUE TITLE
Searching for a user seems broken

### ISSUE THREAD

**Issue by Ademan** [coracle-social/coracle#342]
Searching for a user and clicking on the result in the dropdown does not bring up user profile, it clears the search bar and the search results dropdown.

Similarly hitting "enter" in the search bar will clear the search bar and results.

I get the same behavior in a private window but it could be something stale on my side again...

Coracle `build 68aa48a1`

Chromium `Version 124.0.6367.118 (Official Build) snap (64-bit)` (desktop)

Prior to submitting this report I decided to clear all of my browser's coracle data, when I logged back in (with nos2x) it briefly behaved properly, then stopped working again. For reference my browser currently has only 142 events in the database, in case it's related to that.

**Comment by staab** [comment]
That sounds extremely weird. I wasn't able to reproduce, but I will keep my eye on it.

**Comment by Ademan** [comment]
I've tried to reproduce it again, it's still failing the vast majority of the time, but I did have a string of ~4 successes searching for "nvk" and 1 search for "polyd", and it hasn't worked since. This is in a new chromium "profile" so it ought to be separate afaict.

I also managed to reproduce the issue on firefox 125.0.3 (64-bit) as well, it's definitely not completely consistent maybe it's a timing issue?

It's definitely not 100% of the time but 90%+. It seems to work initially when I test in a new context (new profile, incognito, a different browser like firefox) and then very, very rarely after.

There's no error in the console when it occurs.

**Comment by Ademan** [comment]
This still happens pretty regularly for me, I don't know if you've been able to reproduce it yet. Happy to give any info I can to help you reproduce it.

**Comment by staab** [comment]
I gave it another go, this time logged in with your account (because I thought maybe relay selections might have something to do with it), but no dice, everything worked fine. Have you tried hard-refreshing? I did release a new version the other day with lots of changes that could squash it.

**Comment by Ademan** [comment]
Yeah I've tried clearing every cache and local storage I know how to, to no avail.

What browsers have you tried replicating on?

Just tried again, private window on chromium `Version 124.0.6367.207 (Official Build) snap (64-bit)` completely fresh, replicated first try. I nuked all data from my non-private chromium session, too just for good measure.

**Comment by Ademan** [comment]
https://youtu.be/_mbkRGUY5J8 here's a screen recording in case it's useful and I'm doing something dumb... I actually had a failed recording for this where I had 3-5 successes, but still the vast majority failed to open.

The mobile search seems to operate entirely differently so I wanted to be as clear as possible.

**Comment by Ademan** [comment]
I did notice a bit of mouse movement a couple times I selected a search result, so I tried to hold my mouse as still as possible (two hands lol!) I had a couple successes that way, but even then it was inconsistent, but I wonder if that could be the cause. My mouse *is* pretty sensitive, even on the lowest setting. Maybe monday I can try putting in some logging to see if I'm accidentally triggering a drag or something.

**Comment by staab** [comment]
BIZARRE. Thanks for being so thorough. It looks like you're on Windows? Maybe there's some click handling quirk based on OS? At any rate, I will take a look at the code and see if there's some blur behavior going on that would be causing this.

**Comment by staab** [comment]
Finally was able to track this down. The problem stemmed from not finishing the click fast enough (<100ms). New version is building, hard refresh and let me know if it persists!

**Comment by Ademan** [comment]
Good sleuthing! I wondered if it was timing related initially.

Looks good so far, thanks!
