### ISSUE TITLE
Upload images without blocking compose

### ISSUE THREAD

**Issue by staab** [coracle-social/coracle#349]
Do it like github does

**Comment by peileppe** [comment]
Hello, 

Just discovered coracle .social and it surpasses Primal (or Nostter) in many ways 
Unfortunately Coracle lacks the very simple feature of pasting images into notes
Could this be implemented?

nostr:nevent1qyfhwumn8ghj7ur4wfcxcetsv9njuetn9uq3wamnwvaz7tmjv4kxz7fwwpexjmtpdshxuet59uqsuamnwvaz7tmwdaejumr0dshsz9rhwden5te0d45hxumtv4ujucmvda6kgtcpr9mhxue69uhhqunfweshgefwwfjkgtn8vghxuet59uq3qamnwvaz7tmwdaehgu3wd4hk6tcpz3mhxue69uhhyetvv9ukzcnvv5hx7un89uq3vamnwvaz7tmjv4kxz7fwd4hhxarj9ec82c30qy2hwumn8ghj7un9d3shjtnwdaehgu3wvfnj7qg4waehxw309ahx7um5wghx77r5wghxgetk9uqzqdqsv8tzpjxv3f4xat93jmtzsdryk9prlrvjeec8n2wjrqln6ul2krlmfg

**Comment by staab** [comment]
Yeah, I'll look into it

**Comment by ticruz38** [comment]
#445
