### ISSUE TITLE
Ability to hide side nav menu?

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [coracle-social/coracle#350]
Hello, the new update looks nice but I have problem with 
![image](https://github.com/coracle-social/coracle/assets/28893833/d51084e4-b132-47e9-96e0-1e962b122d12)

why its not expandable when I click on feeds? is it issue on my end? how to collapse/hide it

**Comment by staab** [comment]
Agreed, I'll look at hiding this.

**Comment by staab** [comment]
I've gone ahead and hidden the menu in the next release, should be out soon.
