### ISSUE TITLE
feat(nip-64): Display Chess (PGN) messages

### ISSUE THREAD

**Issue by theborakompanioni** [coracle-social/coracle#351]
In order for [NIP-64](https://github.com/nostr-protocol/nips/pull/1094) to be approved, it needs to be implemented in two clients.
Would coracle be interested in displaying `kind := 64` as chess board in the web interface?

The spec is quite simple and straightforward–so it _should_ be rather easy.
It would need to include a dependency on a library capable of drawing chess boards.
If you are interested, please let me know :pray:

**Comment by staab** [comment]
I think I will give this one a pass, but it is a good reason to prioritize adding nip 89 support in #352

**Comment by theborakompanioni** [comment]
Completely understandable. Thank you for even thinking about it and considering it! :pray:
