### ISSUE TITLE
Missing Nostr address

### ISSUE THREAD

**Issue by remcoros** [coracle-social/coracle#354]
Not sure if I'm doing something wrong, I'm trying different clients.

But using coracle, it doesn't show my NIP05 address:

![image](https://github.com/coracle-social/coracle/assets/130373/1f789f27-b2ba-4437-b50e-2352c1d530a1)

![image](https://github.com/coracle-social/coracle/assets/130373/f4bdec15-3a84-4af5-9c2b-eaea1f295d9c)

Note it says: "No Nostr address found."

But when I go edit the details:

![image](https://github.com/coracle-social/coracle/assets/130373/ab1cac26-0b99-449a-a9c6-ba6fca29b0e7)

It is there already!

This is how my profile looks on primal:

![image](https://github.com/coracle-social/coracle/assets/130373/7d5708b4-bae8-40b1-acb1-2d3984eaf9d3)

My npub: npub14mgq3zmg7wc4g5exw6yztlfaypapcvee06quc5msdqujpa6e5d4sztw00t

Any idea?

**Comment by remcoros** [comment]
Figured it out.

dufflepud makes requests to my lnurlp endpoint, but that is blocked by Cloudflare as "Bot traffic". So it came without any info.

Leaving this open, since you might want to know that Cloudflare blocks these requests by default I suppose. (I have no custom rules or advanced firewall enabled, just a free account with defaults)

**Comment by staab** [comment]
Interesting, thanks for digging in and figuring that out. It's probably a result of poor caching + a suspicious user agent string on dufflepud's part. It would be good to use a more robust proxy.

**Comment by remcoros** [comment]
Any open proxy service like that will eventually be blocked by cloud providers I think, as it's just too easy to abuse open proxies.

Why does the lnurlp request need to go to a proxy? I thought some apps only do this when the initial request fails due to wrongly configured http headers and only use a proxy service as a fallback. that might be an idea for coracle?

**Comment by staab** [comment]
It's for two reasons: privacy (the fbi nip05 trick didn't work on coracle users), and to reduce the number of hits on the nip05 servers (rather than every individual user hitting the nip05, the proxy only hits it once every so often).

**Comment by staab** [comment]
Looks like this is working ok, if sporadically. Closing this with a pinkie promise that I won't forget dufflepud is sub-par.
