### ISSUE TITLE
perepetual load screen keypub

### ISSUE THREAD

**Issue by alltheseas** [coracle-social/coracle#357]
<img width="940" alt="Screenshot 2024-06-04 at 8 46 23 AM" src="https://github.com/coracle-social/coracle/assets/64376233/fb968e0c-ffb0-44ba-ab74-61406d9f6655">

MacOS 14.5
Brave 1.66.113

**Comment by staab** [comment]
Added some error handling, also new issues can go here: https://github.com/coracle-social/keypub
