### ISSUE TITLE
DM read more here link is dead end

### ISSUE THREAD

**Issue by alltheseas** [coracle-social/coracle#360]
<img width="340" alt="Screenshot 2024-06-08 at 8 49 40 PM" src="https://github.com/coracle-social/coracle/assets/64376233/9ea5fa90-44d8-4f67-b691-0a54c06d6b54">

<img width="772" alt="Screenshot 2024-06-08 at 8 50 23 PM" src="https://github.com/coracle-social/coracle/assets/64376233/199a2c20-ea5a-4e58-8d2e-b06f7c22983f">

**Comment by alltheseas** [comment]
@staab is NIP-44 (stated as supported in Coracle) compatible with NIP-17?

**Comment by staab** [comment]
fixed in the next release. To answer your question, NIP 17 is built on NIP 44.
