### ISSUE TITLE
"Lost" DM

### ISSUE THREAD

**Issue by alltheseas** [coracle-social/coracle#361]
_what happened_

1. I sent a DM to a npub using coracle.

2. (Maybe Coracle loaded a new version?)

3. I cannot see the DM referenced in 1. above in my 'Messages' tab in Coracle neither in conversations, nor requests. Other DMs are accessible in the messages tab.

4. I can access DM by going to the "channel" link in my browser history.

**Comment by staab** [comment]
This is likely to be fixed with the next release, coming this week if all goes well.
