### ISSUE TITLE
Minimum WoT score is not being applied correctly

### ISSUE THREAD

**Issue by DireMunchkin** [coracle-social/coracle#364]
I'm frequently seeing posts that should be well below the Minimum WoT score that still are displayed. I currently have it set to 1, but here for example [here](https://coracle.social/notes/nevent1qyvhwumn8ghj7un9d3shjtnndehhyapwwdhkx6tpdshszythwden5te0dehhxarj9emkjmn99uqsuamnwvaz7tmwdaejumr0dshsz9thwden5te0wfjkccte9ejxzmt4wvhxjme0qythwumn8ghj7un9d3shjtnwdaehgu3wvfskuep0qy08wumn8ghj7en9v4j8xtnwdaehgu3wvfskuep0wphhqatvv9eqzxrhwden5te0wfjkccte9e3h2unjv4h8gtnx095j7qgnwaehxw309ahkvenrdpskjm3wwp6kytcpr9mhxue69uhkc6t8dp6xu6twvaex2mrp0yhxxmmd9uq3camnwvaz7tmjv4kxz7fwdehhxarj9ejxjun9vd6x7une9uqzquslk7urtdwtgr0j9x00s9dzymdrrvzyv0lahg964w6wp59p5al87mqfys) you have spam account with -3 score still in the replies.

![Screenshot from 2024-06-11 22-14-28](https://github.com/coracle-social/coracle/assets/1665676/3d8f7709-2116-4ad5-b580-8d9877839899)

**Comment by staab** [comment]
Thanks, I'll look into it

**Comment by staab** [comment]
This is fixed in the next release, thanks for reporting it!

**Comment by DireMunchkin** [comment]
Hello again,
I'm seeing what looks like a regression on this bug - I can't see the number any more but it looks like a zero.

I had WoT threshold set to 10 when the screenshot was taken. I also tried hard refresh and clearing local storage a couple of times.

Here's the event: `note162urk82emx0d8498yrlmynpfydgnnj32q7ehm88wwja29fvs4wksd006qy`

![Screenshot from 2024-09-19 20-50-43](https://github.com/user-attachments/assets/163108c9-ee8e-40fa-be9f-0319a44a4db3)

**Comment by staab** [comment]
Thanks, this was a regression related to the fix above, whacking moles today 😂 Should be fixed momentarily.

**Comment by DireMunchkin** [comment]
Hello again, looks like something broke here again:

![Image](https://github.com/user-attachments/assets/88f92931-7af6-43d9-b4c6-94e09da82bda)

**Comment by staab** [comment]
Thanks! Fixed this, I'll have it out later today.
