### ISSUE TITLE
Show notices to users

### ISSUE THREAD

**Issue by staab** [coracle-social/coracle#371]
Maybe via hud. If there's an error related to a note they've published, show that more prominently. A good test case is sending nip 72 meta to damus.

**Comment by ticruz38** [comment]
A note that fails to broadcast to any relay is displayed as such:

<img width="288" alt="Screenshot 2024-11-20 at 18 11 59" src="https://github.com/user-attachments/assets/44d12c23-408a-47ba-971f-5d4a17553ea7">

In that case it's a timeout, for all relays. 

Should we use a toast if any specific reason is sent back by all or some relay that would give us a better hint as to why the note failed?

**Comment by staab** [comment]
Ok, here's what I'm thinking. 

-[ ] Leave the HUD alone, but make the dialog a tabbed view, with "Events", "Connections", and "Notices".
- [ ] Events would be the current view.
- [ ] Connections would have a set of stats boxes at the top for the quality of various connections. Basically the same logic as the status dot on relay cards, but for all connections available in `pool`, sorted by connection quality descending.
- [ ] Add a "warnings" badge to RelayCard that displays if there have been notices or refused events. If you click on it, it opens the notices tab filtered down to that relay. Probably create an entirely new relay card, since that component is getting pretty overloaded and will have to be re-worked next release anyhow.
- [ ] On the "notices" tab show a multi-select at the top which allows the user to pick 0 or more relay urls from the pool. Below, show a list of notices for that relay ordered chronologically descending, or "No notices found" if not.
