### ISSUE TITLE
Follow list duplicate tags

### ISSUE THREAD

**Issue by mikedilger** [coracle-social/coracle#373]
I am following 204 people.  This was my follow list as of yesterday:  663874847eb98c514a6c31cd1de0a2fd289ec46002101f2be131c3910768cb4b

In coracle I clicked to follow somebody.  Then gossip showed I was following 409 people!  This was the follow list event:
3637eb93314eff361f91eef54357471296d72f8d67b8a0848b91dacf8f54f265

I've republished my follow list so neither of those events is the latest and might not be easily findable anymore depending on whether relays keep replaced events for searching by id.

Gossip was counting "p" tags without deduplicating them.  Coracle seems to have duplicated all 204 original p tags (making 408) and then added the one I followed (making 409 tags).

Probably doesn't break nostr but probably could be better.

**Comment by staab** [comment]
Thanks, I had noticed this but thought I had fixed it. I think it may happen only in edge cases. I'll review it.
