### ISSUE TITLE
Coracle sites not loading (coracle.social & app.coracle.social)

### ISSUE THREAD

**Issue by Arvin21M** [coracle-social/coracle#375]
@staab FYI, please see GIF of experience below within CDN link. This is the 2nd day has not been loading for me. 
Tried various browsers.

https://cdn.satellite.earth/250a67c37f8ad7c21f50318defddf9b0a5b71a9cd80e30fa6944c1b617363059.gif

**Comment by staab** [comment]
Odd, are you using a VPN or anything?

**Comment by Arvin21M** [comment]
Not using VPN. Tried laptop over Wifi, using incognito and standard from various browsers. Also tried mobile data only on phone, over Safari, but still getting the same issue.

**Comment by staab** [comment]
Could you send me a screenshot of your devtools?

**Comment by Arvin21M** [comment]
Sure. This is the console view from Google Chrome.

![image](https://github.com/coracle-social/coracle/assets/141419722/0ffef6c9-887b-4863-8274-0478f9e5a025)
![image](https://github.com/coracle-social/coracle/assets/141419722/4a8098b3-b2eb-422c-8690-5e1b9b4a6c02)

**Comment by Arvin21M** [comment]
Forgot to send Network view. Here goes:

![image](https://github.com/coracle-social/coracle/assets/141419722/c47c7675-6d6f-454c-b50c-586cf35695bd)
![image](https://github.com/coracle-social/coracle/assets/141419722/b4fc43ca-b5de-48ba-8837-466e62d5a110)

**Comment by staab** [comment]
Thanks for the extra information! Looks like this only happens when you're not logged in. Pushing a fix for this now.

**Comment by Arvin21M** [comment]
Awesome! Thanks.
