### ISSUE TITLE
Coracle does not publish a kind 10050 for NIP17 DMs

### ISSUE THREAD

**Issue by jeremyd** [coracle-social/coracle#378]
It should help users pick a relay and publish these events to be fully compliant with NIP17 spec.
Related: https://github.com/coracle-social/coracle/issues/209

**Comment by staab** [comment]
Coracle does publish 10050's based on the "inbox" chip under "Relays". If no 10050 is published for any participant, messages default to nip 04 messages. This could be improved in the following ways:

- Show a warning if someone tries to send a nip17 message but doesn't have a 10050
- You can't send nip04 in group messages anyway, so account for `pubkeys.length > 2` in the nip44 condition, and disable the nip04 toggle.

@SamSamskies

**Comment by jeremyd** [comment]
Ah, ok, I had just been going through user feedback when I did a survey of nip17 clients, they don't tend to setup their relays. Thanks for the info, since this option exists, I will close this ticket.

**Comment by staab** [comment]
I've hijacked this issue, so keeping it open 😂

**Comment by jeremyd** [comment]
cool, glad you did, I was going to say you're welcome to reopen :partying_face: I tend to close issues the second they meet my expectation hehe.

**Comment by SamSamskies** [comment]
> Coracle does publish 10050's based on the "inbox" chip under "Relays". If no 10050 is published for any participant, messages default to nip 04 messages. This could be improved in the following ways:
> 
> * Show a warning if someone tries to send a nip17 message but doesn't have a 10050
> * You can't send nip04 in group messages anyway, so account for `pubkeys.length > 2` in the nip44 condition, and disable the nip04 toggle.
> 
> @SamSamskies

@staab so what should happen if the user tries to send a group message and they don't have a 10050? Shouldn't the textfield also be disabled since they can't send a message? Should there be some kind of message telling them they need to add inbox relays in order to send a group message?

**Comment by staab** [comment]
- If it's a message to a single recipient, the toggle should be set to nip 04 and disabled. On hover, a popover should be shown with a CTA to go to the relays page and choose an inbox relay. If they choose not to upgrade they can still send legacy messages.
- If it's a group message, the toggle should be hidden entirely.
- If they click "create" on the messages page, and add >1 recipient but either the user or one of the recipients has no 10050, show a warning and disable the confirm button.
- If they're already in a group chat, let them compose messages and click submit. If the user or one of the recipients has no 10050, show an informative warning message with "send anyway" and "cancel" buttons. Tell them which user is missing the 10050, and if it's the current user, provide a link to the relays page.

@dtonon anything to add?

**Comment by jeremyd** [comment]
I did go to the relays page to see if I could check for the inbox settings, but not via the hint, there didn't seem to be anywhere to add or differentiate an inbox relay when going there directly.. Also, that page is HUGE, i guess it's all relays currently connected in one big list..

**Comment by staab** [comment]
Once you "join" one, it'll show up in the top section and should allow you to turn on "inbox" mode using the chip in the card.

**Comment by SamSamskies** [comment]
> * If it's a message to a single recipient, the toggle should be set to nip 04 and disabled. On hover, a popover should be shown with a CTA to go to the relays page and choose an inbox relay. If they choose not to upgrade they can still send legacy messages.

@staab when closing the relays popup after setting up inbox relays, the Channel component doesn't re-render so the toggle stays disabled even though the user now has a 10050. Any ideas on how to make the component re-render?

Another thing I noticed is that if you remove all your inbox relays, the 10050 event still exists. It just doesn't have any tags. Shouldn't Coracle request deletion of the 10050 event when removing the last inbox relay? The spec says that the list of relays is required.

**Comment by SamSamskies** [comment]
> @staab when closing the relays popup after setting up inbox relays, the Channel component doesn't re-render so the toggle stays disabled even though the user now has a 10050. Any ideas on how to make the component re-render?

I figured out a solution for this.

> Another thing I noticed is that if you remove all your inbox relays, the 10050 event still exists. It just doesn't have any tags. Shouldn't Coracle request deletion of the 10050 event when removing the last inbox relay? The spec says that the list of relays is required.

I'm just going to check to make sure that each 10050 has relay tags for now.

**Comment by staab** [comment]
> Shouldn't Coracle request deletion of the 10050 event when removing the last inbox relay?

Probably, but it's probably more to handle the edge case on read than on write. I wouldn't mind deleting the 10050 when it's empty too, but the logic for that has been generalized, so might be a little annoying to build.

**Comment by SamSamskies** [comment]
@staab I can't load any group chats. I created a group chat with 3 of my accounts using Coracle. I checked the messages for all 3 accounts and they were there the first time I checked. Then I tried loading it in development, but the group chat wouldn't load in any of the accounts. Then I checked back on prod and now the group chat doesn't show in any of the accounts anymore. Any idea what the problem could be? Are there only certain relays that support group chats? I've selected wss://relay.nostr.band and wss://relay.damus.io as inbox relays for all 3 accounts.

**Comment by SamSamskies** [comment]
Hmmm I tried it a couple more times and now it's working. Hopefully this last one doesn't disappear like the other ones before I finish testing.

**Comment by staab** [comment]
There's a bug where coracle drops the indexeddb database sometimes, which borks message syncing. Plus, many relays reject 1059's, or rate limit them, which makes things tricky. Let me know if you stumble across any leads on that database bug.
