### ISSUE TITLE
Tweak profile

### ISSUE THREAD

**Issue by staab** [coracle-social/coracle#383]
- On note cards, show the nip05 next to the pubkey. Only show the domain if it's an underscore address.
- On profile page, follow the same pattern, plus a copy icon next to the pubkey

![Screenshot 2024-07-18 at 10 52 17 AM](https://github.com/user-attachments/assets/6a22af9d-68b8-47a0-9c53-50cdcc2c5fb6)

**Comment by dtonon** [comment]
Ops, I didn't see that and I just [opened a more detailed issue](https://github.com/coracle-social/coracle/issues/384).
I close this one.
