### ISSUE TITLE
Popover with profile details in the feed

### ISSUE THREAD

**Issue by dtonon** [coracle-social/coracle#385]
This proposal introduces an informative popover as middle step before accessing the full user profile page; this permits to have some useful informations at hand without switching context. It is strongly related to the update by https://github.com/coracle-social/coracle/issues/384.

The popup is activated by clicking the name/WoT area; it is closed using the X on the top-right or clicking outside it.
The profile pic instead can brings directly to the profile page, acting like a shortcut.

The NIP-05 is highlighted and linked to the domain only if it can be useful to identify better the user (see again https://github.com/coracle-social/coracle/issues/384).

Bonus: show when _name/display_name_ have been changed.

<img width="760" alt="Screenshot 2024-07-19 at 17 35 39" src="https://github.com/user-attachments/assets/328ae546-fe67-44e4-be63-ed642bea30f3">
<br/><br/>

<img width="760" alt="Screenshot 2024-07-19 at 17 37 53" src="https://github.com/user-attachments/assets/869b2ec1-13c7-40cf-b8dd-baf2f7d47915">

**Comment by dtonon** [comment]
@staab I know you don't like this solution, but let's keep it on hold to see if it can be taken up or improved later.

**Comment by dtonon** [comment]
I forgot to say: the proposed popover should be applied only on desktop. On mobile it would require a bottom up sheet, that has the same context effect as opening the profile.

**Comment by dtonon** [comment]
I copy here my thoughts about the cons:

> Profile picture is a non-obvious click target

It is only a shortcut, so it is not a critical block, and it is actually intended to have a low click surface.
But as soon the user discover it by accident, it remember the trick.

> All the information in the popup should be on the profile page, rendering it redundant

True, even if considering the notes, the metadata are a minimal part of the whole profile (that I will redesign), so the second click bring to a non-repetitive page.

> Showing on hover would be too annoying

Sure, in fact I proposed a click.

> so it's a click vs a click

Oh, my mind was already floating in a future reality where the profile doesn't open in a bottom sheet modal!

**Comment by staab** [comment]
What if we made the click on the name/profile go to the profile page, but a click on the wot score open the info popover? It already currently works this way, we'd just be adding more information to the popover.

**Comment by dtonon** [comment]
Yes, I think it's fine.
Then we can eventually evaluate which are the most frequent actions and activate the popover or link to the profile accordingly.

**Comment by ticruz38** [comment]
what are the date below name and about? The last time it has been updated?
