### ISSUE TITLE
Get rid of displayList

### ISSUE THREAD

**Issue by staab** [coracle-social/coracle#388]
Use new `Intl.ListFormat(getLocale(), {style: "long", type: "conjunction"})` instead. Stick it in a utility function.

**Comment by zmjohnso** [comment]
Been thinking about this one. Using `Intl.ListFormat()` feels like a good idea and would work well but alone it does not cover the same functionality as your `displayLists` library function. Notably this part of the logic: 
```typescript
else if (xs.length > n + 2) {
    return `${xs.slice(0, n).join(", ")}, ${conj} ${xs.length - n} others`
  }
  ```
  Utilizing `Intl.ListFormat()` the updated logic could look something like this:
  ```typescript
export default <T>(xs: T[], conj = "and", n = 6, locale = "en-US") => {
  if (xs.length > n + 2) {
    const formattedList = new Intl.ListFormat(locale, { style: "long", type: "conjunction" }).format(xs.slice(0, n));
    return `${formattedList}, ${conj} ${xs.length - n} others`;
  }

  return new Intl.ListFormat(locale, { style: "long", type: "conjunction" }).format(xs);
}
```
Do you think it makes more sense to move this logic into the project via a utility function, or update it in your `hurdak` library method?

**Comment by staab** [comment]
Hey Zack, sorry I missed this comment, I think moving this into the project itself would be best. That way i18n stuff isn't leaking into the utility library, which increases its scope significantly.
