### ISSUE TITLE
Alternative views for custom feeds

### ISSUE THREAD

**Issue by dtonon** [coracle-social/coracle#389]
The first version of the custom feeds exploration view, using a secondary sidebar, seems too unbalanced:

![image](https://github.com/user-attachments/assets/d48a02d5-0a27-4613-a09d-c17c575d108c)

We can move the main area to the left recovering some space from the sidebar, but the effect remains the same, especially on large screens:

![image](https://github.com/user-attachments/assets/6a36781b-3b11-42e6-9e1b-682e8ee202da)

The problem with the current solution is that feeds are not visible at all, and this is a shame since they are a powerful feature.

We have at least two more options:

1) Let the user navigate a sub-menu inside the same sidebar, collapsing the first one in a narrow column:

![image](https://github.com/user-attachments/assets/51ef26df-c914-446c-bbb2-e3d3360b01f4)

The main problem of this solution is that this specific view should be the initial one, so the user would start with the main menu collapsed, and this is a poor UI/UX. To solve that, we could put on the main menu two items: "Main feed" and "Custom feeds".

2) An alternative solution is to move the secondary nav to the right, with the same width or slightly narrower than the first, centering the main block:

![image](https://github.com/user-attachments/assets/e58d2e48-865a-47cb-a756-eec23ff641a3)
 
The main problem of this solution is that the central block would move to the right when changing section (e.g. notification, messages, etc), giving an annoying "bouncing" feeling; the solution could be to always keep a secondary "ghost" column, to be used possibly in other contexts, for example to display the note details (liked and zapped by, nevent, etc).

**Comment by dtonon** [comment]
@staab thoughts?

**Comment by staab** [comment]
> The main problem of this solution is that this specific view should be the initial one

I am planning to add a new people-centric view based on keypub.coracle.social. I'm inclined to make this the default view, which would solve this particular point.

In general, rather than a sidebar I think some kind of control at the top of the feeds page makes the most sense, like we currently have, but with feed presets represented as well. Here's a slight evolution:

![Screenshot 2024-07-22 at 12 16 09 PM](https://github.com/user-attachments/assets/9cb182a9-a6c7-43ac-9a2e-0b3bf791f149)
![Screenshot 2024-07-22 at 12 16 04 PM](https://github.com/user-attachments/assets/978e9ed1-4dce-4b26-a11a-bd9c59be12c2)

**Comment by staab** [comment]
An attempt:

https://image.nostr.build/16172f9fbe685c4111ba021b6c2a12e95ce0081285cf6a521887371cb7df101b.png

People don't like (or don't understand) this:

nostr:nevent1qvzqqqqqqypzp978pfzrv6n9xhq5tvenl9e74pklmskh4xw6vxxyp3j8qkke3cezqy88wumn8ghj7mn0wvhxcmmv9uq32amnwvaz7tmjv4kxz7fwv3sk6atn9e5k7tcpr4mhxue69uhkzem9de6x7unpdenk2tnwdaehgu339e3k7mf0qy88wumn8ghj7ctywfjjuum49uq35amnwvaz7tmrv93ksef39ec8y6tdv9kzumn9wshhvvgqyzewydmapdm8asqk7xtm8kpkvkdk2kkclux3kd5y2f4g4jfz65ty2sgtz2p

This has helped me realize that there are a few different problems to solve here though:

- Surface feeds the user already has customized so they get used more
- Surface the fact that you can save feeds
- Surface the fact that you can browse/bookmark feeds

**Comment by dtonon** [comment]
We have so much space to the left and right of the feed that it makes little sense to me to take up vertical space.
The only possible alternative I can see is using a dropdown like you proposed [here](https://github.com/coracle-social/coracle/issues/389#issuecomment-2243647429), so the selected feed is clearly displayed.

Furthermore, I would reduce the priority of the “Filters” button; the ability to completely edit a feed is interesting, but I doubt it is really used. Perhaps a simple search is sufficient to filter the content of a feed, so the  “Filters” button can simply be removed.
Instead, the "Create new feed" CTA should be prominent, so the user can easily start a new fresh filter, and then decide if to save or discard it.

**Comment by ticruz38** [comment]
on a personal note, I think Coracle would look great as a twitter deck
- it is widely considered a nostr "super client"
- it already has built-in tool to build list and filter out feeds
- it would make sense for the desktop version to offer many thread in the same window

**Comment by staab** [comment]
Thanks @dtonon that gives me some ideas.

On the idea of a twitter deck layout, I've thought about that in the past. And it might be worth doing. I personally hate it though, and so I would probably stop using my own client if we did that. Maybe it could be an option users could toggle.

On the topic of a sidebar, I want to solve the mobile design first, then add a sidebar afterwards. A sidebar would probably make sense for wide screens, but we also need a solution on mobile

**Comment by staab** [comment]
Closing this with 7ca09df2f7b7405b45ada8b6522ecfb393a39441. We can continue refining this as we have ideas and users have pain points. Opened #483 to cover the sidebar topic.

**Comment by ticruz38** [comment]
> On the idea of a twitter deck layout, I've thought about that in the past. And it might be worth doing. I personally hate it though, and so I would probably stop using my own client if we did that. Maybe it could be an option users could toggle.

This could be sort of opt-in, defaulting to one feed with the possibility to add more, the view would scroll horizontally to show the other feeds
On mobile you would just swap between your feed, like in Damus, passing from note and note and reply for example
