### ISSUE TITLE
Restyling user profile page

### ISSUE THREAD

**Issue by dtonon** [coracle-social/coracle#390]
This proposal aims to restyle the user profile page with the goal to make the `npub` and the `follow`/`message` CTAs more prominent. The NIP-05 visualization follow the rules defined in #384.
Following and followers are integrated in the horizontal menu, and should be listed on the same view, avoiding opening a different interface (the bottom-up sheet).

![image](https://github.com/user-attachments/assets/5e33c06d-1faa-40f2-9b8f-aa5ac87a243b)

For followed profiles, the "Following" button is hidden and the "Unfollow" action is present just in the top-right menu, because it is a low frequency action.

![image](https://github.com/user-attachments/assets/c75fd709-74ca-46b5-97ec-80bf22c0ac78)

**Comment by staab** [comment]
Beautiful, far superior.

> For followed profiles, the "Following" button is hidden and the "Unfollow" action is present just in the top-right menu, because it is a low frequency action.

I don't know about this. What happens when they click follow? Does the button disappear, or change to unfollow until they re-visit the page? I would find it frustrating to not be able to find the undo button, and it seems unnecessary to hide it.

**Comment by dtonon** [comment]
> I don't know about this. What happens when they click follow? 

Good question. I was thinking of fading out the Follow button and moving up the Message one. Keeping the Unfollow button until the next visit is worse, because the subsequent absence can be disorienting, the user should learn that Unfollow is always inside the "more action" dropdown.
Instead, leaving the Unfollow always visible make it too prominent, and prone to a misclick if one wants to click on Message.
I also thought about the need to undo, but I suppose it is a very infrequent case, the user should know how to solve the problem.

**Comment by dtonon** [comment]
I forgot the user's own profile!
An "Edit" button replace Follows/Message, and the top-right dropdown actions are hidden.

![image](https://github.com/user-attachments/assets/036393a6-ca4c-44d5-a1fb-f5aaeef9cb34)
