### ISSUE TITLE
Restyling user profile page - relays

### ISSUE THREAD

**Issue by dtonon** [coracle-social/coracle#394]
Related to the new profile (#390), this is the relay section.
I would let the user see the relay info (NIP-11) inline.

![image](https://github.com/user-attachments/assets/e91fc6a6-8773-4932-b197-7b67325dcf18)

![image](https://github.com/user-attachments/assets/e54b8329-f644-4655-a3e9-e558af5a9f37)

**Comment by ticruz38** [comment]
what is the explore button for? send me to the relay marketplace?

**Comment by staab** [comment]
Currently clicking on a relay card opens a special purpose relay feed, we should redirect to the main feed page instead though, with a relay-specific feed loaded.

**Comment by ticruz38** [comment]
> Currently clicking on a relay card opens a special purpose relay feed
When I click on the Relay URL or name, it does open a modal with 2 tabs, notes and review.

So clicking explore would send me to the main feed with notes from this relay only?

**Comment by staab** [comment]
> So clicking explore would send me to the main feed with notes from this relay only?

That's what I was thinking, but on reviewing the code it's not trivial. Just send them to the current relay detail page.
