### ISSUE TITLE
Forum style

### ISSUE THREAD

**Issue by maxbrito500** [coracle-social/coracle#395]
Hello,

Coracle on the current style imitates twitter/hackernews but we still need a forum equivalent.

The reason is because users go to specialized relays (e.g. a product forum) and expect to find different topic sections presented to them. This way they know where to write the details of their questions/feedback.

Notes are sorted according to tags. For examples "Hardware->Cellphones->Fairphone->Fairphone5".

This is needed because people want to browse what is available on each section and read the posts inside, even if they were written for a very specific topic years ago.

I am writing a forum converter, where posts on the forum database can be converted to Nostr data. If you have any other suggestions, please do let me know.

Thank you.

**Comment by staab** [comment]
This is a fine idea, but not related to Coracle, you might try posting on nostrtalk.org instead.
