### ISSUE TITLE
Can no longer create or like notes.

### ISSUE THREAD

**Issue by sdgathman** [coracle-social/coracle#399]
Last week, coracle was requesting authorization from nos2x-fox 4 or 5 times.  Annoying but not that big a deal.  That is now fixed, but coracle no longer allows posting or liking notes.  The heart icon or the send icon do not have the hover animation they did last week, and clicking on them has no effect.

I went over to snort.social, and that still lets me post and like.  That client uses like 60% cpu, so not a long term solution.

**Comment by staab** [comment]
It sounds like Coracle thinks you're logged in with your pubkey rather than extension, can you try logging out/in again?

**Comment by sdgathman** [comment]
Logging out allows me to create notes and likes again.
