### ISSUE TITLE
Topics with non-ascii characters not getting parsed correctly

### ISSUE THREAD

**Issue by staab** [coracle-social/coracle#412]
note182qq9lm9r3gq6qq4axgaer59lx8ay9hs5xy8xt4k6xv0f45dermquqtuud

I don't think this is an accurate description of the problem, I wonder if it's a result of typing in the hashtag that the tag gets mangled. At any rate, the new editor will fix this, or at least create a different problem.

**Comment by ticruz38** [comment]
awaiting #437 if the problem remains

**Comment by ticruz38** [comment]
Fixed with #486
