### ISSUE TITLE
Fix broken hyperlinks when they end with a period

### ISSUE THREAD

**Issue by GlenCooper** [coracle-social/coracle#417]
When someone posts a note with a web address as the last thing in a sentence, and ends that sentence with a period, the hyperlink is broken since it includes the ending period.  The hyperlink should not include the trailing period.

EXAMPLE:
https://coracle.social/notes/nevent1qythwumn8ghj7un9d3shjtnswf5k6ctv9ehx2ap0qy2hwumn8ghj7un9d3shjtnyv9kh2uewd9hj7qghwaehxw309a3xjarrda5kuetj9eek7cmfv9kz7qgkwaehxw309ahx7um5wghxgct5vyhxsct4wvhsz8thwden5te0dehhxarj9e3xjarrda5kuetj9eek7cmfv9kz7qg4waehxw309aex2mrp0yhxummnw3ezucn89uq3vamnwvaz7tmzv4mx7tnwdaehgu339e3k7mf0qy2hwumn8ghj7mn0wd68ytn5dpsku6ewv46j7qgnwaehxw309ahkvenrdpskjm3wwp6kytcpr9mhxue69uhhyetvv9ujuumwdae8gtnnda3kjctv9uq3samnwvaz7tmwdaehgu3wvekhgtnhd9azucnf0ghsz8thwden5te0dehhxarj9ekh2arfdeuhwctvd3jhgtnrdakj7qg4waehxw309ahx7um5wghx77r5wghxgetk9uq3uamnwvaz7tmwdaehgu3dwp6kytnhv4kxcmmjv3jhytnwv46z7qgkwaehxw309ahx7um5wghxjmn0wd6xztnrvvhszyrhwden5te0dehhxarj9ekk7mf0qydhwumn8ghj7un9d3shjtnwdaehgunsd3jkyuewvdhk6tcpr3mhxue69uhhyetvv9ujucnfw33k76twwpshy6ewvdhk6tcpr9mhxue69uhhwetvvdhk6efwdehhxarj9emkjmn99uq3zamnwvaz7tmwdaehgu3wwa5kuef0qyghwumn8ghj7mn0wd68ytnvv9hxgtcqyq5s23n0gdexyygug5fypfsqaa2ev8e4egt5pqlaxnkct5tkdp5qzznxs3e

The last sentence in that note is:
>You can see how I have my njump hyperlink at the bottom of glencooper.com.

[Coracle.social](https://Coracle.social) is incorrectly building the hyperlink as:
[https://glencooper.com.](https://glencooper.com.)

... when it should actually be:
[https://glencooper.com](https://glencooper.com)

This bad behavior is highlit in this archived page: https://archive.ph/0pe3L#selection-499.1-499.16

**Comment by GlenCooper** [comment]
I'm not sure how to add a label to this issue, but it is a Bug.  It should be labeled as such.

**Comment by staab** [comment]
Thanks, fixed in the next release.
