### ISSUE TITLE
Too hard to enter nsec

### ISSUE THREAD

**Issue by mikedilger** [coracle-social/coracle#427]
I can't paste, I can't see what I'm typing, and it won't scan a QR code.  By the time I get to the end of trying to type my nsec I have made several mistakes but cannot see them to correct them.

**Comment by staab** [comment]
Can you confirm that long-pressing on the text area doesn't work?


![recording](https://github.com/user-attachments/assets/f9aeb4b5-7f7f-4a3c-acfb-6f4bd4403576)

**Comment by mikedilger** [comment]
Long pressing gives me just the word "Autofill".  Maybe something weird is going on with my phone, I dunno.  I presume it is on my end.

**Comment by staab** [comment]
Weird, thanks for reporting anyway, I'll keep an eye out for it

**Comment by staab** [comment]
Actually, I just looked into this more, and it looks like "paste" won't come up if there's nothing on your clipboard. Maybe your password manager or OS is clearing the clipboard?

**Comment by mikedilger** [comment]
Ok I got some other paste field in Coracle to show 'Paste', so I think you are right. I must not have cut properly.
