### ISSUE TITLE
fix profile search results w/ increased search results x WOT: dergigi

### ISSUE THREAD

**Issue by alltheseas** [coracle-social/coracle#433]
_what happens_

in a sea of impersonators, i cannot find real dergigi

![Screenshot from 2024-10-03 15-03-33](https://github.com/user-attachments/assets/de8ab698-9746-4e08-a7de-fb17d001f8b9)

_commentary_

recently this is an issue on damus as well for certain accounts that have a lot of imposters. in the case of damus, will suggested that expanding the search results will yield the "real" dergigi, and bring him to the top of the search results.

**Comment by staab** [comment]
Not much I can do, since "dergigi" isn't his username:

<img width="401" alt="Screenshot 2024-10-03 at 3 09 32 PM" src="https://github.com/user-attachments/assets/7f7839cf-cab0-4b41-a433-38c3f2d40260">

**Comment by staab** [comment]
Well, ok, maybe this is interesting, since his nip05 does say dergigi.

**Comment by staab** [comment]
This will be fixed in the next release, thanks for reporting it.

d747424c287a6479e6ed2fb552467c3830521268

**Comment by alltheseas** [comment]
nice!
