### ISSUE TITLE
Feature Request: Load calendar events for npub

### ISSUE THREAD

**Issue by tohrxyz** [coracle-social/coracle#434]
I love many of the Coracle's features, such as Calendar. I've noticed you can save url for specific event like `coracle.social/events/naddr:...` , this gave me an idea.

If some organization is posting events (real events like meetup and stuff), then it would be extremely helpful to be able to navigate and list directly that org's events in the calendar.

like `coracle.social/events/npub...`

currently it doesn't support npub as url param

( working version in #435 )

**Comment by staab** [comment]
See comments on #435, this isn't currently planned and there are probably better ways to do it. But I understand the need for it and hope to support a more complete solution in the future, possibly in flotilla.
