### ISSUE TITLE
Coracle submits invalid REQ filters to relays

### ISSUE THREAD

**Issue by pbennett** [coracle-social/coracle#44]
Looking at relay filter date, I've noticed that coracle submits invalid NIP-01 REQ filters.
Two examples (replacing the searched pubkey)
```
{"kinds":[42],"#e":["xxxxx"],"since":null,"until":null,"limit":50}
{"kinds":[4],"#p":["xxxxx"],"authors":[null]}
```

null is not a valid value for these filters.  Instead, since, until, authors shouldn't be specified in the filter at all.

**Comment by staab** [comment]
Fixed in the next release, thanks for the report.
