### ISSUE TITLE
Remove NIP 04

### ISSUE THREAD

**Issue by staab** [coracle-social/coracle#444]
It's time, also add warnings to NIP 17 stuff if inbox relays are missing.

- [ ] Remove code to send nip 04 messages
- [ ] Continue downloading and displaying nip04s
- [ ] Warn the user if there are missing inbox relays (see flotilla for an example)

**Comment by ticruz38** [comment]
do we still use legacy message when there is more than one recipient, ie group message? Seems like it was the case before.

**Comment by staab** [comment]
No, legacy messages are only for one-to-one chats, group chats are always nip 17
