### ISSUE TITLE
onboarding: profiles appear marked as "followed" without me having followed these profiles

### ISSUE THREAD

**Issue by alltheseas** [coracle-social/coracle#454]
_what happens_

When I am creating new keys on Coracle, during the suggested follow onboarding flow before I have followed any profiles, some profiles appear labeled as "FOLLOWED". 

_what I expect to happen_

I don't expect anyone to be auto-followed (I am not sure if this is a bug, or if auto-following is taking place).

![image](https://github.com/user-attachments/assets/f66192d7-e3ad-4a70-8516-7067ea2845a9)

**Comment by staab** [comment]
This is a display bug, there is a fix in the next release.
