### ISSUE TITLE
Can't manage inbox relays

### ISSUE THREAD

**Issue by DireMunchkin** [coracle-social/coracle#461]
I'm noticing a problem with my relay management in Coracle - I have two relays extra that I'm pretty sure I did not add: wss://relay.0xchat.com and wss://auth.nostr1.com. Both of them are set as Inbox relays, and are the only ones that are like that. When I try to leave these relays nothing happens.

Also wss://auth.nostr1.com has been down consistently so I always have a orange dot on the relays menu warning me about it.

**Comment by ticruz38** [comment]
#428

**Comment by staab** [comment]
This should actually be fixed in the next release. I'm not sure where the relays are coming from, but the problem with removing them is due to failing to normalize urls before comparing them.

**Comment by ticruz38** [comment]
is this fix in the last welshman version @staab ?

**Comment by staab** [comment]
It was in engine/commands: fb00f51d5a83b062c844aa011a3229b0ba6a6540
