### ISSUE TITLE
Slow performance in Coracle on Firefox

### ISSUE THREAD

**Issue by DireMunchkin** [coracle-social/coracle#462]
I've noticed Coracle after a while starts getting incredibly slow - I'm specifically noticing this on my desktop browser (LibreWolf, a Firefox variant). On mobile I haven't seen this issue. What seems to trigger it pretty reliably is scrolling far backwards in the timeline, then the page will eventually freeze for 1-5 seconds and the browser will show a "this page is slowing down Firefox" warning.

**Comment by DireMunchkin** [comment]
This is actually noticeably better on 0.5.0!

**Comment by staab** [comment]
Awesome! I definitely found some places to improve performance.
