### ISSUE TITLE
Give users more control over which relays to connect

### ISSUE THREAD

**Issue by hasundue** [coracle-social/coracle#48]
I had look at the developer-tool's console while Coracle loads my feed, and found Coracle trying to connect all the relays it knows, regardless of my relay configuration.

I suppose it is intended to reduce delays for fetching replies, but in general I don't believe it a good idea in several reasons like:

- It increases the CPU and bandwidth usages
- Most of connections end up with being useless, especially if you use aggregating relays like filter.nostr.wine
- It seems to conflict with the design or philosophy of nostr, or decentralization

How about subscribing additional relays on demand, and making that behavior optional and controllable by users?
Appreciate if you took this in consideration.

My environment FYI: 
```
Vivaldi	6.0.2979.15 (Stable channel) stable (64-bit) 
Revision	48baf1f6e9cb9f18b98a815e1ae64ed52b71222f
OS	Linux
JavaScript	V8 11.2.214.14
User Agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
```

**Comment by staab** [comment]
This is actually by design following NIP-65. Feeds contact write relays for the people you're following, and event context follows event hints. It would be interesting to add a mechanism for optimized or static relay selection, but I'm not sure how useful that would be.

**Comment by hasundue** [comment]
Ohhh I see. Thank you for the answer. The NIP-65 doc convinced me that it's more decentralized way, though I still want some control over what I do. Maybe I'm experimenting privately.
