### ISSUE TITLE
Not able to find intended people on 'Add List'

### ISSUE THREAD

**Issue by paulosacramento** [coracle-social/coracle#52]
I tried to add people that I follow to a list, but their names did not show up.

![Screen Shot 2023-05-12 at 21 07 58](https://github.com/coracle-social/coracle/assets/76049494/afa16fdf-0fa7-46a3-80b5-5ad14c69c6d9)
For example, here I am looking for '@NVK', a user I follow. His name is now displayed.

![Screen Shot 2023-05-12 at 21 07 48](https://github.com/coracle-social/coracle/assets/76049494/d489c598-2a1a-4ff1-8a18-784eda70ba27)
In this case, I was searching for '@rablle' who I also follow. I could not find him.

**Comment by nvk** [comment]
Why would you follow @nvk?

**Comment by staab** [comment]
Thanks for the report, I'm not currently able to get to this, but hopefully will in a few weeks.

**Comment by staab** [comment]
Fixed this last week. Current solution is search will show people you follow first. This is just a first pass, much more should be done to improve robustness and recognizability of search.
