### ISSUE TITLE
Color next to relay selector

### ISSUE THREAD

**Issue by weex** [coracle-social/coracle#54]
On https://coracle.social/relays each relay has a colored left border which seems to be stable per relay but has unclear meaning. Even though a full spectrum is represented, users may be biased toward green or against red colored ones.

Proposed solutions:
Color by performance, other documented quality, or remove colors.

**Comment by staab** [comment]
I'm going to keep this as is, the color is a hash of the relay url to help with quick recognizability in the future when relays are actually differentiated.
