### ISSUE TITLE
Opening a thread should change the URL

### ISSUE THREAD

**Issue by tsauvajon** [coracle-social/coracle#59]
When I go to https://coracle.social/notes, and then click on a note to make the thread pop up, the URL should be updated to https://coracle.social/nevent1xxxxxxxx instead of https://coracle.social/notes#m=1.

This would serve several purposes:
- I could more easily share the link
- I would have the note in my browser history allowing to go back to the previous page (= previous note)
- I would be able to bookmark notes with my browser
- I would be able to reload the page or reload the browser and stay on the same note

**Comment by staab** [comment]
Agreed. This is not easy though, I'll have to meditate upon it.

**Comment by staab** [comment]
Fixed in the next release
