### ISSUE TITLE
"Share" menu option under the 3 dots menu gives wrong note ID

### ISSUE THREAD

**Issue by tsauvajon** [coracle-social/coracle#60]
The event ID given by the Share button is incorrect:
![share-coracle-note](https://github.com/coracle-social/coracle/assets/22611118/5e122910-f5ff-45c6-8365-9a034954482d)

On the other hand, clicking on the date (top right of the note) updates the URL to the correct event:
![it works](https://github.com/coracle-social/coracle/assets/22611118/4fbd45b2-73f9-4b63-981d-1a5c075b7272)

---

I get theses IDs:
- When clicking the Share button: nevent1qqstednpfhlajfp2ruwhsartc62ns8z69vsztr5rp37yu5esf5hxtnqppadk7cn2v43hggz0vf4x2cm5t54lazke
- When clicking the date: nevent1qqstednpfhlajfp2ruwhsartc62ns8z69vsztr5rp37yu5esf5hxtnqpz3mhxue69uhhyetvv9ujuerpd46hxtnfdustrux5

**Comment by staab** [comment]
Thank you, fixed in the next release.
