### ISSUE TITLE
Lists don't populate from kind 30000 notes

### ISSUE THREAD

**Issue by weex** [coracle-social/coracle#61]
I created some lists as kind 30000 notes but they don't show up in the Feeds kebab menu. It would be really cool if these lists were interoperable with other clients. Probably requires a confirmation on deletion since I deleted one and was worried that it might have blasted one of my kind 30000 lists.

**Comment by staab** [comment]
I'll have to think about this, Coracle uses kind 30001 lists specifically, and the interface I've built wouldn't work with kind 30000.

**Comment by staab** [comment]
I've moved away from kind 30000s, but they're still supported for now in order to avoid deleting people's feeds. I'll migrate these to normal lists eventually.
