### ISSUE TITLE
Mark all read

### ISSUE THREAD

**Issue by Giszmo** [coracle-social/coracle#62]
Hopping between different clients on different devices I use "mark all read" a lot on my messages but coracle doesn't have that feature.

**Comment by Giszmo** [comment]
I think Snort and Astral just locally cache. No idea about other apps. If you store it in a custom event, please nip it.

**Comment by staab** [comment]
I'm using nip 78 right now, but at some point we'll hammer something interoperable out.

**Comment by staab** [comment]
Fixed a while ago, for interoperable app data see #77
