### ISSUE TITLE
Coracle failed to publish my note and lost it - or can I recover it?

### ISSUE THREAD

**Issue by fr4nzap** [coracle-social/coracle#64]
I just typed an elaborate reply to a note and clicked Send.

I see the message: "Published to 0/11 relays (11 pending)"

It's stuck there. All relays seem to be disconnected. All activity in the console is dead.

So I went to the feed, now there is read activity but my reply still unpublished. It's been like that for more than 10 minutes.

I'd like to get my note and post it using another client. How do I do? (I did not close the window.)

**Comment by staab** [comment]
You should be able to find it using `db.userEvents.all().sort((a, b) => a.created_at > b.created_at ? 1 : -1)` in the console, it'll be one of the last events. I need to work on socket re-connection stuff, this happens on occasion.
