### ISSUE TITLE
Data loss: Relays page overwrites wrong relays

### ISSUE THREAD

**Issue by franzaps** [coracle-social/coracle#65]
1. I set my preferred relays in https://metadata.nostr.com  – I verify 10002 events are properly sent to all relays
2. Load https://coracle.social/relays
3. Coracle does not properly read relays from my metadata:
  - The UI shows very different relays to the ones I previously saved
  - An inspection on the only common relay (wss://relay.damus.io) shows a REQ asking for `kinds: [0, 2, 3, 10001, 10002]` for 3 different  `authors` but my pubkey is not there
4. Changes in Coracle (adding/leaving relay) trigger 10002 events which overwrite my relay settings
5. Back to https://metadata.nostr.com/ I refresh the page and see I lost my preferred relays. Fortunately I can restore latest versions from there

Coracle seems to correctly write but incorrectly read user relays from 10002 events.

Thanks for you work on it, I really like the client and want to keep using it.

**Comment by staab** [comment]
This will be much improved in the next release. I've opted to skip NIP 05 for now, since finding your handle requires having access to your kind 0, which is not likely to happen unless you already know which relays to use, or have an index which contains the data you want.
