### ISSUE TITLE
Bad URL parser

### ISSUE THREAD

**Issue by paulmillr** [coracle-social/coracle#66]
see web+nostr://nevent1qqs2cxz5m7yy2jp8jxzdm68e7skpql55v5cgehcg2g0e3ul3gfutxmgpz3mhxue69uhhyetvv9ujuerpd46hxtnfdujvpjlm

it thinks url is (https://a.com), instead of just https://a.com

**Comment by staab** [comment]
Fixed in the next release, I created #69 to handle more edge cases.
