### ISSUE TITLE
<Failed to decrypt message: Error: window.nostr call already executing> error when using NIP07

### ISSUE THREAD

**Issue by f90fwT** [coracle-social/coracle#67]
When opening messages, if you don't have accept automatically for NIP07, you get the `<Failed to decrypt message: Error: window.nostr call already executing>` error.

[20230719002140.webm](https://github.com/coracle-social/coracle/assets/137908879/25fa880c-17a5-4423-afef-396687daea59)

But even when i gave all the permissions, some messages still don't load!

**Comment by staab** [comment]
This is a known issue, I finally found the solution last week, so it'll be fixed in the next release. Thanks for the report!
