### ISSUE TITLE
Followers / following count not displayed

### ISSUE THREAD

**Issue by pinheadmz** [coracle-social/coracle#68]
I have two nostr IDs. One profile has the follower stats:

https://coracle.social/npub1mxvj8xkw6534udzml3def2vtc4w4hr50eawglmssuw5zwt2ytvmqh00ah8

The other does not:

https://coracle.social/npub18l0cks7jum44nlpena7trwqey0galuppt4z6z8surunesfl24tvqr04ml9

I can't figure out what I did to hide my follower count

**Comment by staab** [comment]
Follower stats are downloaded on demand, and sometimes don't come through for various reasons. The next version will handle this a little differently by showing a download icon so stats can be pulled lazily, so closing for now.
