### ISSUE TITLE
Solve messaging

### ISSUE THREAD

**Issue by staab** [coracle-social/coracle#70]
A few different possibilities here:

- Link to other apps
- Embed other apps (e.g. blowater)
- Prioritize the feature

It's not a huge feature, but it is a drag, and not really the main focus of Coracle.

**Comment by staab** [comment]
Yep, see #122 for some of that, this issue is more about the cost of maintaining these features. Adding chat/dms to a popup like fb/twitter could be a good pattern though that would demand less and work better.

**Comment by staab** [comment]
Closing this, having removed nip 28 public chat as a non-goal. However, I think DMs are worth keeping.

**Comment by VictorieeMan** [comment]
Yes, DM is baseline appreciated by all users. While Public chat is sort of a minority niche use case. Good call.
